### ISSUE TITLE
stdin / out got stuck in wenv

### ISSUE THREAD

**Issue by stuaxo** [pleiszenburg/wenv#12]
I was playing with launching wenv from a python subprocess and `wenv python` started getting stuck.

i.e.  before, I could launch `wenv python` and get a python shell, but now when I run it nothing happens until I kill the process.

I'm sure if I reboot it will start working again.

I tried doing `kill wenv -9` and `kill python.exe -9` but it still behaves in the same way.

I need a bit more experimentation to repro the bug, in the meantime I'm wondering which process to kill to get it working again.

**Comment by stuaxo** [comment]
Closing, unless I manage to reproduce.

Upgrading wine did something that fixed things.

**Comment by s-m-e** [comment]
There is usually an instance of `wineserver` running in a separate process. Ideally, it should terminate together with your Wine process (`python.exe`) but sometimes it gets stuck. Check all running processes (`ps -ef`) for Wine-related stuff, especially `wineserver` and other `*.exe` things, and kill all of it one by one. Then you should have a level playing field and be able to start again without a reboot.

I have seen this before. It is usually triggered by some Wine issue/bug, then Wine does not cleanly quit and the user is unable to start new Wine processes (or, in other words, new ones get stuck).

**Comment by stuaxo** [comment]
I'd forgotten about wineserver, I will try that next time.
