### ISSUE TITLE
wenv init as non root user

### ISSUE THREAD

**Issue by stuaxo** [pleiszenburg/wenv#4]
If I install wenv as a user it installs to ./.local/bin/wenv:
```
$ pip3 install wenv
$ which wenv
/home/stu/.local/bin/wenv
```

However `wenv init` tries to install use the system directory, in this case it should run successfully, and probably setup in `.local/share/wenv`

**Comment by s-m-e** [comment]
Yes, indeed. For a user install, Python's `sys.prefix` still points to `/usr` (instead of `~/.local/`. Some logic is needed to detect where and how the package is installed to avoid this.

**Comment by stuaxo** [comment]
I wonder what pip does to work out where to install things ?

**Comment by s-m-e** [comment]
There is a `--user` option for `pip install`. I'd bet it can be triggered through a configuration file or environment variable. What OS / distro are you running on?

**Comment by stuaxo** [comment]
Ubuntu,  `--user` seems to be the default, though I'm at work so check try right now.

**Comment by s-m-e** [comment]
> Ubuntu, `--user` seems to be the default [...]

Thanks, I have not seen this before. Will try in a VM.

In the meantime, I just pushed a possible fix to `develop`. You can try it by installing it from github: `pip install -U git+https://github.com/pleiszenburg/wenv.git@develop`

It should auto-detect a user installation and use `site.USER_BASE` instead of `sys.prefix`.

**Comment by stuaxo** [comment]
Cheers I'll give it a go later, and double check my assumptions.

**Comment by stuaxo** [comment]
Great, that works.

According to this bug - https://github.com/eight04/vpip/issues/4

The rule is:

If the `sys.prefix` is not writeable and `site.ENABLE_USER_SITE` is set then try the directory `--user` would use.

The dest directory is described in [PEP 0370](https://www.python.org/dev/peps/pep-0370/#windows-notes)

The destination directory is the same on mac and linux, I guess wenv is Windows  a bit exotic, but you never know(?).

**Comment by s-m-e** [comment]
Implemented in v0.2.0, released.
